# Generated by Django 5.0.7 on 2024-08-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
