# Generated by Django 5.0.7 on 2024-08-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='full_name',
        ),
    ]
