# Generated by Django 5.0.7 on 2024-08-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_author_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
