# Generated by Django 5.0.7 on 2024-08-03 19:35

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True, validators=[books.validators.validate_isbn]),
        ),
    ]
